require("dotenv").config()
const express = require("express")
const authRoutes = require("./modules/auth/auth.routes")
const incidentRoutes = require("./modules/incidents/incident.routes")
const app =express()
const whatsappRoutes = require("./modules/whatsapp/whatsapp.routes")
app.use(express.json())
app.use("/api/auth", authRoutes)
app.use("/api/incidents",incidentRoutes)
app.use("/api/whatsapp",whatsappRoutes)
module.exports = app
